### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by avoinea** [eaudeweb/plone.ro#1]
http://plone.eaudeweb.ro/stiri
- Loading-ul e verde (install eea.faceted.blue theme)

http://plone.eaudeweb.ro/descopera
- Add CSS:

``` css
  .descopera-heading {
      background: #329FD7;
      color: white;
  }
```
